// Auto-generated by generate_bootkick_stubs.py — DO NOT EDIT.
// Extracted from /Users/joseph/Documents/opensource_workspace/panda/board/drivers/bootkick.h:5-68
// Regenerate: python3 generate_bootkick_stubs.py > bootkick_e2e.gen.c

// ---- Promoted globals (was static locals in bootkick_tick) ----
  uint16_t e2e_bootkick_last_serial_ptr = 0;
  uint8_t e2e_waiting_countdown = 0;
  uint8_t e2e_boot_reset_countdown = 0;
  uint8_t e2e_bootkick_harness_prev = HARNESS_STATUS_NC;
  bool e2e_bootkick_ign_prev = false;
  BootState e2e_boot_state = BOOT_BOOTKICK;

// ---- Transformed bootkick_tick (state promoted to accessible globals) ----
void bootkick_tick(bool ignition, bool recent_heartbeat) {
  BootState boot_state_prev = e2e_boot_state;
  const bool harness_inserted = (harness.status != e2e_bootkick_harness_prev) && (harness.status != HARNESS_STATUS_NC);

  if ((ignition && !e2e_bootkick_ign_prev) || harness_inserted) {
    // bootkick on rising edge of ignition or harness insertion
    e2e_boot_state = BOOT_BOOTKICK;
  } else if (recent_heartbeat) {
    // disable bootkick once openpilot is up
    e2e_boot_state = BOOT_STANDBY;
  } else {

  }

  /*
    Ensure SOM boots in case it goes into QDL mode. Reset behavior:
    * shouldn't trigger on the first boot after power-on
    * only try reset once per bootkick, i.e. don't keep trying until booted
    * only try once per panda boot, since openpilot will reset panda on startup
    * once BOOT_RESET is triggered, it stays until countdown is finished
  */
  if (!bootkick_reset_triggered && (e2e_boot_state == BOOT_BOOTKICK) && (boot_state_prev == BOOT_STANDBY)) {
    e2e_waiting_countdown = 20U;
  }
  if (e2e_waiting_countdown > 0U) {
    bool serial_activity = uart_ring_som_debug.w_ptr_tx != e2e_bootkick_last_serial_ptr;
    if (serial_activity || current_board->read_som_gpio() || (e2e_boot_state != BOOT_BOOTKICK)) {
      e2e_waiting_countdown = 0U;
    } else {
      // try a reset
      if (e2e_waiting_countdown == 1U) {
        e2e_boot_reset_countdown = 5U;
      }
    }
  }

  // handle reset state
  if (e2e_boot_reset_countdown > 0U) {
    e2e_boot_state = BOOT_RESET;
    bootkick_reset_triggered = true;
  } else {
    if (e2e_boot_state == BOOT_RESET) {
      e2e_boot_state = BOOT_BOOTKICK;
    }
  }

  // update state
  e2e_bootkick_ign_prev = ignition;
  e2e_bootkick_harness_prev = harness.status;
  e2e_bootkick_last_serial_ptr = uart_ring_som_debug.w_ptr_tx;
  if (e2e_waiting_countdown > 0U) {
    e2e_waiting_countdown--;
  }
  if (e2e_boot_reset_countdown > 0U) {
    e2e_boot_reset_countdown--;
  }
  current_board->set_bootkick(e2e_boot_state);
}

// ---- e2e_tick_handler_1hz — mirrors main.c 1Hz decimated block ----
static void e2e_tick_handler_1hz(void) {
  // Mirrors: bool started = harness_check_ignition() || ignition_can;
  bool started = e2e_ignition_line;
  // Mirrors: const bool recent_heartbeat = heartbeat_counter == 0U;
  bool recent_heartbeat = heartbeat_counter == 0U;
  // Mirrors: bootkick_tick(started, recent_heartbeat);
  bootkick_tick(started, recent_heartbeat);
  if (heartbeat_counter < UINT32_MAX) {
    heartbeat_counter += 1U;
  }
}

// ---- JNA entry points ----
void jna_tick_handler(void) { e2e_tick_handler_1hz(); }

int jna_get_bootkick_state(void)            { return (int)e2e_boot_state; }
int jna_get_bootkick_reset_triggered(void)   { return (int)bootkick_reset_triggered; }
int jna_get_bootkick_waiting_countdown(void) { return (int)e2e_waiting_countdown; }
int jna_get_bootkick_reset_countdown(void)   { return (int)e2e_boot_reset_countdown; }

void jna_reset_bootkick(void) {
  e2e_boot_state = BOOT_BOOTKICK;
  e2e_bootkick_ign_prev = false;
  e2e_bootkick_harness_prev = HARNESS_STATUS_NC;
  e2e_bootkick_last_serial_ptr = 0;
  e2e_waiting_countdown = 0;
  e2e_boot_reset_countdown = 0;
  bootkick_reset_triggered = false;
  e2e_ignition_line = false;
#if defined(E2E_BOARD_TRES)
  e2e_GPIOB.IDR &= ~(1U << 1);
#elif !defined(E2E_BOARD_RED)
  e2e_GPIOC.IDR |= (1U << 3);
#endif
}
