// Auto-generated by generate_clock_source_stubs.py — DO NOT EDIT.
// Faithful reproduction of real clock_source_set_timer_params() from board/drivers/clock_source.h.
// Regenerate: python3 generate_clock_source_stubs.py > clock_source_e2e.gen.c


// From /Users/joseph/Documents/opensource_workspace/panda/board/drivers/clock_source.h:6
void clock_source_set_timer_params(uint16_t param1, uint16_t param2) {
  // Pulse length of each channel
  register_set(&(TIM1->CCR1), (((param1 & 0xFF00U) >> 8U)*10U), 0xFFFFU);
  register_set(&(TIM1->CCR2), ((param1 & 0x00FFU)*10U), 0xFFFFU);
  register_set(&(TIM8->CCR3), (((param2 & 0xFF00U) >> 8U)*10U), 0xFFFFU);
  // Timer period
  register_set(&(TIM1->ARR),  (((param2 & 0x00FFU)*10U) - 1U), 0xFFFFU);
  register_set(&(TIM1->CCR4), ((TIM1->ARR + 1U) / 2U), 0xFFFFU);
}

