// Auto-generated by generate_fdcan_stubs.py — DO NOT EDIT.
// Faithful reproductions of real firmware FDCAN functions,
// adapted to write to fake FDCAN_GlobalTypeDef instances instead of MMIO.
// Regenerate: python3 generate_fdcan_stubs.py > fdcan_e2e.gen.c


// From /Users/joseph/Documents/opensource_workspace/panda/board/stm32h7/llfdcan.h:7
static bool e2e_fdcan_request_init(FDCAN_GlobalTypeDef *FDCANx) {
  bool ret = true;
  // Exit from sleep mode
  FDCANx->CCCR &= ~(FDCAN_CCCR_CSR);

  // Request init
  uint32_t timeout_counter = 0U;
  FDCANx->CCCR |= FDCAN_CCCR_INIT;
  return ret;
}

// From /Users/joseph/Documents/opensource_workspace/panda/board/stm32h7/llfdcan.h:29
static bool e2e_fdcan_exit_init(FDCAN_GlobalTypeDef *FDCANx) {
  bool ret = true;

  FDCANx->CCCR &= ~(FDCAN_CCCR_INIT | FDCAN_CCCR_CCE);  // HW auto-clears CCE
  uint32_t timeout_counter = 0U;
  return ret;
}

// From /Users/joseph/Documents/opensource_workspace/panda/board/stm32h7/llfdcan.h:47
static bool e2e_llcan_set_speed(FDCAN_GlobalTypeDef *FDCANx, uint32_t speed, uint32_t data_speed, bool non_iso, bool loopback, bool silent) {
  UNUSED(speed);
  bool ret = e2e_fdcan_request_init(FDCANx);

  if (ret) {
    // Enable config change
    FDCANx->CCCR |= FDCAN_CCCR_CCE;

    //Reset operation mode to Normal
    FDCANx->CCCR &= ~(FDCAN_CCCR_TEST);
    FDCANx->TEST &= ~(FDCAN_TEST_LBCK);
    FDCANx->CCCR &= ~(FDCAN_CCCR_MON);
    FDCANx->CCCR &= ~(FDCAN_CCCR_ASM);
    FDCANx->CCCR &= ~(FDCAN_CCCR_NISO);

    // TODO: add as a separate safety mode
    // Enable ASM restricted operation(for debug or automatic bitrate switching)
    //FDCANx->CCCR |= FDCAN_CCCR_ASM;

    uint8_t prescaler = BITRATE_PRESCALER;
    if (speed < 2500U) {
      // The only way to support speeds lower than 250Kbit/s (down to 10Kbit/s)
      prescaler = BITRATE_PRESCALER * 16U;
    }

    // Set the nominal bit timing values
    uint32_t tq = CAN_QUANTA(speed, prescaler);
    uint32_t sp = CAN_SP_NOMINAL;
    uint32_t seg1 = CAN_SEG1(tq, sp);
    uint32_t seg2 = CAN_SEG2(tq, sp);
    uint8_t sjw = MIN(127U, seg2);

    FDCANx->NBTP = (((sjw & 0x7FUL)-1U)<<FDCAN_NBTP_NSJW_Pos) | (((seg1 & 0xFFU)-1U)<<FDCAN_NBTP_NTSEG1_Pos) | (((seg2 & 0x7FU)-1U)<<FDCAN_NBTP_NTSEG2_Pos) | (((prescaler & 0x1FFUL)-1U)<<FDCAN_NBTP_NBRP_Pos);

    // Set the data bit timing values
    if (data_speed == 50000U) {
      sp = CAN_SP_DATA_5M;
    } else {
      sp = CAN_SP_DATA_2M;
    }
    tq = CAN_QUANTA(data_speed, prescaler);
    seg1 = CAN_SEG1(tq, sp);
    seg2 = CAN_SEG2(tq, sp);
    sjw = MIN(15U, seg2);

    FDCANx->DBTP = (((sjw & 0xFUL)-1U)<<FDCAN_DBTP_DSJW_Pos) | (((seg1 & 0x1FU)-1U)<<FDCAN_DBTP_DTSEG1_Pos) | (((seg2 & 0xFU)-1U)<<FDCAN_DBTP_DTSEG2_Pos) | (((prescaler & 0x1FUL)-1U)<<FDCAN_DBTP_DBRP_Pos);

    if (non_iso) {
      // FD non-ISO mode
      FDCANx->CCCR |= FDCAN_CCCR_NISO;
    }

    // Silent loopback is known as internal loopback in the docs
    if (loopback) {
      FDCANx->CCCR |= FDCAN_CCCR_TEST;
      FDCANx->TEST |= FDCAN_TEST_LBCK;
      FDCANx->CCCR |= FDCAN_CCCR_MON;
    }
    // Silent is known as bus monitoring in the docs
    if (silent) {
      FDCANx->CCCR |= FDCAN_CCCR_MON;
    }
    ret = e2e_fdcan_exit_init(FDCANx);
    if (!ret) {
      print(CAN_NAME_FROM_CANIF(FDCANx)); print(" set_speed timed out! (2)\n");
    }
  } else {
    print(CAN_NAME_FROM_CANIF(FDCANx)); print(" set_speed timed out! (1)\n");
  }
  return ret;
}

// From /Users/joseph/Documents/opensource_workspace/panda/board/stm32h7/llfdcan.h:147
static bool e2e_llcan_init(FDCAN_GlobalTypeDef *FDCANx) {
  uint32_t can_number = (uint32_t)(FDCANx - fake_fdcan);
  bool ret = e2e_fdcan_request_init(FDCANx);

  if (ret) {
    // Enable config change
    FDCANx->CCCR |= FDCAN_CCCR_CCE;
    // Enable automatic retransmission
    FDCANx->CCCR &= ~(FDCAN_CCCR_DAR);
    // Enable transmission pause feature
    FDCANx->CCCR |= FDCAN_CCCR_TXP;
    // Disable protocol exception handling
    FDCANx->CCCR |= FDCAN_CCCR_PXHD;
    // FD with BRS
    FDCANx->CCCR |= (FDCAN_CCCR_FDOE | FDCAN_CCCR_BRSE);

    // Set TX mode to FIFO
    FDCANx->TXBC &= ~(FDCAN_TXBC_TFQM);
    // Configure TX element data size
    FDCANx->TXESC |= 0x7U << FDCAN_TXESC_TBDS_Pos; // 64 bytes
    //Configure RX FIFO0 element data size
    FDCANx->RXESC |= 0x7U << FDCAN_RXESC_F0DS_Pos;
    // Disable filtering, accept all valid frames received
    FDCANx->XIDFC &= ~(FDCAN_XIDFC_LSE); // No extended filters
    FDCANx->SIDFC &= ~(FDCAN_SIDFC_LSS); // No standard filters
    FDCANx->GFC &= ~(FDCAN_GFC_RRFE); // Accept extended remote frames
    FDCANx->GFC &= ~(FDCAN_GFC_RRFS); // Accept standard remote frames
    FDCANx->GFC &= ~(FDCAN_GFC_ANFE); // Accept extended frames to FIFO 0
    FDCANx->GFC &= ~(FDCAN_GFC_ANFS); // Accept standard frames to FIFO 0

    uint32_t start_offset = can_number * FDCAN_OFFSET;
    uint32_t end_offset = start_offset + (FDCAN_RX_FIFO_0_EL_CNT * FDCAN_RX_FIFO_0_EL_SIZE);

    // RX FIFO 0
    FDCANx->RXF0C |= (FDCAN_RX_FIFO_0_OFFSET + (can_number * FDCAN_OFFSET_W)) << FDCAN_RXF0C_F0SA_Pos;
    FDCANx->RXF0C |= FDCAN_RX_FIFO_0_EL_CNT << FDCAN_RXF0C_F0S_Pos;
    // RX FIFO 0 switch to non-blocking (overwrite) mode
    FDCANx->RXF0C |= FDCAN_RXF0C_F0OM;

    // TX FIFO (mode set earlier)
    FDCANx->TXBC |= (FDCAN_TX_FIFO_OFFSET + (can_number * FDCAN_OFFSET_W)) << FDCAN_TXBC_TBSA_Pos;
    FDCANx->TXBC |= FDCAN_TX_FIFO_EL_CNT << FDCAN_TXBC_TFQS_Pos;

    // Flush allocated RAM
    end_offset += (FDCAN_TX_FIFO_EL_CNT * FDCAN_TX_FIFO_EL_SIZE);
    for (uint32_t RAMcounter = start_offset; RAMcounter < end_offset; RAMcounter += 4U) {
        *(uint32_t *)(fake_fdcan_sram + RAMcounter) = 0x00000000;
    }

    // Enable both interrupts for each module
    FDCANx->ILE = (FDCAN_ILE_EINT0 | FDCAN_ILE_EINT1);

    FDCANx->IE &= 0x0U; // Reset all interrupts
    // Messages for INT0
    FDCANx->IE |= FDCAN_IE_RF0NE; // Rx FIFO 0 new message
    FDCANx->IE |= FDCAN_IE_PEDE | FDCAN_IE_PEAE | FDCAN_IE_BOE | FDCAN_IE_EPE | FDCAN_IE_RF0LE;

    // Messages for INT1 (Only TFE works??)
    FDCANx->ILS |= FDCAN_ILS_TFEL;
    FDCANx->IE |= FDCAN_IE_TFEE; // Tx FIFO empty

    ret = e2e_fdcan_exit_init(FDCANx);
    if(!ret) {
      print(CAN_NAME_FROM_CANIF(FDCANx)); print(" llcan_init timed out (2)!\n");
    }

    llcan_irq_enable(FDCANx);

  } else {
    print(CAN_NAME_FROM_CANIF(FDCANx)); print(" llcan_init timed out (1)!\n");
  }
  return ret;
}

// From /Users/joseph/Documents/opensource_workspace/panda/board/stm32h7/llfdcan.h:221
static void e2e_llcan_clear_send(FDCAN_GlobalTypeDef *FDCANx) {
  // from datasheet: "Transmit cancellation is not intended for Tx FIFO operation."
  // so we need to clear pending transmission manually by resetting FDCAN core
  FDCANx->IR |= 0x3FCFFFFFU; // clear all interrupts
  bool ret = e2e_llcan_init(FDCANx);
  UNUSED(ret);
}

// From /Users/joseph/Documents/opensource_workspace/panda/board/drivers/fdcan.h:5
static bool e2e_can_set_speed(uint8_t can_number) {
  bool ret = true;
  FDCAN_GlobalTypeDef *FDCANx = &fake_fdcan[can_number];
  uint8_t bus_number = BUS_NUM_FROM_CAN_NUM(can_number);

  ret &= e2e_llcan_set_speed(
    FDCANx,
    bus_config[bus_number].can_speed,
    bus_config[bus_number].can_data_speed,
    bus_config[bus_number].canfd_non_iso,
    can_loopback,
    can_silent
  );
  return ret;
}

// From /Users/joseph/Documents/opensource_workspace/panda/board/drivers/fdcan.h:255
bool can_init(uint8_t can_number) {
  bool ret = false;


  if (can_number != 0xffU) {
    FDCAN_GlobalTypeDef *FDCANx = &fake_fdcan[can_number];
    ret &= e2e_can_set_speed(can_number);
    ret &= e2e_llcan_init(FDCANx);
    // in case there are queued up messages
  }
  return ret;
}

// From /Users/joseph/Documents/opensource_workspace/panda/board/drivers/fdcan.h:21
void can_clear_send(FDCAN_GlobalTypeDef *FDCANx, uint8_t can_number) {

  // Resetting CAN core is a slow blocking operation, limit frequency
    can_health[can_number].can_core_reset_cnt += 1U;
    e2e_llcan_clear_send(FDCANx);
}

