#!/usr/bin/env python3
"""
Generate e2e-adapted power_save stub from real firmware source.

Extracts set_power_save_state() from board/sys/power_saving.h
so the e2e test always runs the SAME logic as production.

Usage: python3 generate_power_save_stubs.py > power_save_e2e.gen.c
"""

import re
import sys

PROJECT_ROOT = "/Users/joseph/Documents/opensource_workspace/panda"

POWER_SAVING_H = f"{PROJECT_ROOT}/board/sys/power_saving.h"

FUNC_NAME = "set_power_save_state"


def read_file(path):
    with open(path) as f:
        return f.read()


def find_function(source, func_name):
    """Find function body in source, returning (start_line_idx, end_line_idx)."""
    lines = source.split("\n")
    pattern = re.compile(
        r"^\s*void\s+" + re.escape(func_name) + r"\s*\("
    )
    for i, line in enumerate(lines):
        if pattern.match(line):
            # find opening brace
            j = i
            while j < len(lines) and "{" not in lines[j]:
                j += 1
            if j >= len(lines):
                break
            depth = 0
            for k in range(j, len(lines)):
                for ch in lines[k]:
                    if ch == "{":
                        depth += 1
                    elif ch == "}":
                        depth -= 1
                        if depth == 0:
                            return i, k
            break
    return None, None


def generate():
    header = """// Auto-generated by generate_power_save_stubs.py — DO NOT EDIT.
// Faithful reproduction of real set_power_save_state() from board/sys/power_saving.h.
// Regenerate: python3 generate_power_save_stubs.py > power_save_e2e.gen.c

"""

    source = read_file(POWER_SAVING_H)
    start, end = find_function(source, FUNC_NAME)
    if start is None:
        print(f"ERROR: {FUNC_NAME} not found in {POWER_SAVING_H}", file=sys.stderr)
        sys.exit(1)

    lines = source.split("\n")[start:end + 1]

    result = [header]
    result.append(f"// From {POWER_SAVING_H}:{start + 1}")
    result.extend(lines)
    result.append("")

    return "\n".join(result)


if __name__ == "__main__":
    print(generate())
