#!/usr/bin/env python3
"""
Generate e2e enter_stop_mode() verbatim from board/sys/power_saving.h.
All hardware register operations are preserved as-is.

Usage: python3 generate_enter_stop_mode_stubs.py > enter_stop_mode_e2e.gen.c
"""

import re
import sys

PROJECT_ROOT = "/Users/joseph/Documents/opensource_workspace/panda"
POWER_SAVING_H = f"{PROJECT_ROOT}/board/sys/power_saving.h"
FUNC_NAME = "enter_stop_mode"


def read_file(path):
    with open(path) as f:
        return f.read()


def find_function(source, func_name):
    lines = source.split("\n")
    pattern = re.compile(r"^\s*static\s+void\s+" + re.escape(func_name) + r"\s*\(.*\)")
    for i, line in enumerate(lines):
        if pattern.match(line):
            j = i
            while j < len(lines) and "{" not in lines[j]:
                j += 1
            if j >= len(lines):
                break
            depth = 0
            for k in range(j, len(lines)):
                for ch in lines[k]:
                    if ch == "{":
                        depth += 1
                    elif ch == "}":
                        depth -= 1
                        if depth == 0:
                            return i, k
            break
    return None, None


def generate():
    header = """// Auto-generated by generate_enter_stop_mode_stubs.py — DO NOT EDIT.
// Verbatim from board/sys/power_saving.h. Regenerate via build.sh.
"""
    source = read_file(POWER_SAVING_H)
    start, end = find_function(source, FUNC_NAME)
    if start is None:
        print(f"ERROR: {FUNC_NAME} not found in {POWER_SAVING_H}", file=sys.stderr)
        sys.exit(1)

    lines = source.split("\n")[start:end + 1]
    func_decl = lines[0].replace("static ", "").rstrip().rstrip('{').rstrip()

    body_start = next(i for i, l in enumerate(lines) if "{" in l)
    body_lines = lines[body_start + 1:-1]

    result = [header, f"// From {POWER_SAVING_H}:{start + 1}", func_decl, "{"]
    result.extend(body_lines)
    result.append("}")
    return "\n".join(result)


if __name__ == "__main__":
    print(generate())
