#!/usr/bin/env python3
"""Generate e2e-adapted update_can_health_pkt stub from real firmware source.

Extracts update_can_health_pkt() from board/drivers/fdcan.h
and applies CANIF_FROM_CAN_NUM → &fake_fdcan[] transform.

Usage: python3 generate_can_health_stubs.py > can_health_e2e.gen.c
"""

import re
import sys

PROJECT_ROOT = "/Users/joseph/Documents/opensource_workspace/panda"

FDCAN_H = f"{PROJECT_ROOT}/board/drivers/fdcan.h"

FUNC_NAME = "update_can_health_pkt"


def read_file(path):
    with open(path) as f:
        return f.read()


def find_function(source, func_name):
    lines = source.split("\n")
    pattern = re.compile(r"^\s*void\s+" + re.escape(func_name) + r"\s*\(")
    for i, line in enumerate(lines):
        if pattern.match(line):
            j = i
            while j < len(lines) and "{" not in lines[j]:
                j += 1
            if j >= len(lines):
                break
            depth = 0
            for k in range(j, len(lines)):
                for ch in lines[k]:
                    if ch == "{":
                        depth += 1
                    elif ch == "}":
                        depth -= 1
                        if depth == 0:
                            return i, k
            break
    return None, None


def generate():
    header = """// Auto-generated by generate_can_health_stubs.py — DO NOT EDIT.
// Faithful reproduction of real update_can_health_pkt() from board/drivers/fdcan.h.
// Regenerate: python3 generate_can_health_stubs.py > can_health_e2e.gen.c

"""

    source = read_file(FDCAN_H)
    start, end = find_function(source, FUNC_NAME)
    if start is None:
        print(f"ERROR: {FUNC_NAME} not found in {FDCAN_H}", file=sys.stderr)
        sys.exit(1)

    lines = source.split("\n")[start:end + 1]

    # Transform CANIF_FROM_CAN_NUM → &fake_fdcan[]
    transformed = []
    for line in lines:
        line = re.sub(
            r"\bCANIF_FROM_CAN_NUM\s*\(\s*(\w+)\s*\)",
            r"&fake_fdcan[\1]",
            line,
        )
        transformed.append(line)

    result = [header]
    result.append(f"// From {FDCAN_H}:{start + 1}")
    result.extend(transformed)
    result.append("")

    return "\n".join(result)


if __name__ == "__main__":
    print(generate())
