#!/usr/bin/env python3
"""
Generate board_stubs_e2e.gen.c — extracts set_bootkick, set_amp_enabled,
and enable_can_transceiver from production board headers.

Why not #include the headers directly?
  Board init functions (cuatro_init etc.) reference dozens of STM32H7-specific
  macros (GPIO_AF8_SAI4, GPIO_SPEED_VERY_HIGH, ...) that would need stubs.

Usage: python3 generate_board_stubs.py > board_stubs_e2e.gen.c
"""

import re
import sys

PROJECT_ROOT = "/Users/joseph/Documents/opensource_workspace/panda"
BOARDS = {
    "cuatro": f"{PROJECT_ROOT}/board/boards/cuatro.h",
    "tres": f"{PROJECT_ROOT}/board/boards/tres.h",
    "red": f"{PROJECT_ROOT}/board/boards/red.h",
}

FUNCS = ["set_bootkick", "set_amp_enabled", "enable_can_transceiver"]


def read_file(path):
    with open(path) as f:
        return f.read()


def extract_function(source, board_name, func_name):
    """Extract the board-specific function body."""
    full_name = f"{board_name}_{func_name}" if board_name != "red" else f"{board_name}_{func_name}"
    if board_name == "tres" and func_name in ("set_amp_enabled",):
        return None  # tres uses unused_set_amp_enabled

    pattern = re.compile(r"static\s+void\s+" + re.escape(full_name) + r"\s*\(.*?\)")
    for m in pattern.finditer(source):
        start = m.start()
        # find opening brace
        i = source.index("{", start)
        depth = 1
        j = i + 1
        while depth > 0 and j < len(source):
            if source[j] == "{":
                depth += 1
            elif source[j] == "}":
                depth -= 1
            j += 1
        body = source[start:j]
        # Remove 'static' so function has external linkage
        body = body.replace("static ", "", 1)
        return body
    return None


def generate():
    header = """// Auto-generated by generate_board_stubs.py — DO NOT EDIT.
// Extracts set_bootkick, set_amp_enabled, enable_can_transceiver
// from production board headers. Regenerate via build.sh.
"""

    result = [header]

    for board in ["cuatro", "tres", "red"]:
        board_upper = board.upper()
        source = read_file(BOARDS[board])

        result.append(f"#ifdef E2E_BOARD_{board_upper}")
        result.append(f"// From {BOARDS[board]}")

        for func in FUNCS:
            func_body = extract_function(source, board, func)
            if func_body:
                result.append(func_body)
            elif board == "red" and func in ("set_bootkick", "set_amp_enabled"):
                result.append(f"// {board}_{func}: unused on red")
            elif board == "tres" and func == "set_amp_enabled":
                result.append(f"// tres_{func}: unused on tres")

        result.append(f"#endif // E2E_BOARD_{board_upper}")
        result.append("")

    return "\n".join(result)


if __name__ == "__main__":
    print(generate())
