#!/usr/bin/env python3
"""Generate harness_detect_e2e.gen.c from production board/drivers/harness.h.

Extracts harness_detect_orientation() verbatim and adds a JNA entry point wrapper.
No static locals to promote — the function is included as-is.

Usage: python3 generate_harness_stubs.py > harness_detect_e2e.gen.c
"""

import re
import sys
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.normpath(os.path.join(SCRIPT_DIR, "../../../.."))
HARNESS_H = os.path.join(PROJECT_ROOT, "board", "drivers", "harness.h")

FUNC_NAME = "harness_detect_orientation"


def find_function(lines, func_name):
    """Find start and end line indices (0-based) of a function definition."""
    pattern = re.compile(rf"^\s*static\s+uint8_t\s+{re.escape(func_name)}\s*\(")
    for i, line in enumerate(lines):
        if pattern.match(line):
            # Find opening brace
            j = i
            while j < len(lines) and "{" not in lines[j]:
                j += 1
            if j >= len(lines):
                break
            depth = 0
            for k in range(j, len(lines)):
                for ch in lines[k]:
                    if ch == "{":
                        depth += 1
                    elif ch == "}":
                        depth -= 1
                        if depth == 0:
                            return i, k
            break
    return None, None


def generate():
    if not os.path.exists(HARNESS_H):
        print(f"ERROR: {HARNESS_H} not found", file=sys.stderr)
        sys.exit(1)

    with open(HARNESS_H) as f:
        source = f.read()

    lines = source.split("\n")
    start, end = find_function(lines, FUNC_NAME)

    if start is None:
        print(f"ERROR: {FUNC_NAME} not found in {HARNESS_H}", file=sys.stderr)
        sys.exit(1)

    func_lines = lines[start:end + 1]

    output = []
    output.append("// Auto-generated by generate_harness_stubs.py — DO NOT EDIT.")
    output.append(f"// Extracted from {HARNESS_H}:{start + 1}-{end + 1}")
    output.append("// Regenerate: python3 generate_harness_stubs.py > harness_detect_e2e.gen.c")
    output.append("")
    output.append("// ---- Production harness_detect_orientation (verbatim) ----")
    output.extend(func_lines)
    output.append("")
    output.append("// ---- JNA entry point ----")
    output.append("// Calls the production harness_detect_orientation() and updates harness.status.")
    output.append("void jna_detect_harness_orientation(void) {")
    output.append("  harness.status = harness_detect_orientation();")
    output.append("}")

    return "\n".join(output)


if __name__ == "__main__":
    print(generate())
