#!/usr/bin/env python3
"""Generate verbatim update_can_health_pkt() from board/drivers/fdcan.h.

Extracts update_can_health_pkt() verbatim — no transforms needed since
CANIF_FROM_CAN_NUM resolves through FDCAN1/2/3 macros that already point to fake_fdcan[].

Usage: python3 generate_can_health_stubs.py > can_health_e2e.gen.c
"""

import re
import sys

PROJECT_ROOT = "/Users/joseph/Documents/opensource_workspace/panda"

FDCAN_H = f"{PROJECT_ROOT}/board/drivers/fdcan.h"

FUNC_NAME = "update_can_health_pkt"


def read_file(path):
    with open(path) as f:
        return f.read()


def find_function(source, func_name):
    lines = source.split("\n")
    pattern = re.compile(r"^\s*void\s+" + re.escape(func_name) + r"\s*\(")
    for i, line in enumerate(lines):
        if pattern.match(line):
            j = i
            while j < len(lines) and "{" not in lines[j]:
                j += 1
            if j >= len(lines):
                break
            depth = 0
            for k in range(j, len(lines)):
                for ch in lines[k]:
                    if ch == "{":
                        depth += 1
                    elif ch == "}":
                        depth -= 1
                        if depth == 0:
                            return i, k
            break
    return None, None


def generate():
    header = """// Auto-generated by generate_can_health_stubs.py — DO NOT EDIT.
// Verbatim extraction of update_can_health_pkt() from board/drivers/fdcan.h.
// Regenerate: python3 generate_can_health_stubs.py > can_health_e2e.gen.c

"""

    source = read_file(FDCAN_H)
    start, end = find_function(source, FUNC_NAME)
    if start is None:
        print(f"ERROR: {FUNC_NAME} not found in {FDCAN_H}", file=sys.stderr)
        sys.exit(1)

    lines = source.split("\n")[start:end + 1]

    result = [header]
    result.append(f"// From {FDCAN_H}:{start + 1}")
    result.extend(lines)
    result.append("")

    return "\n".join(result)


if __name__ == "__main__":
    print(generate())
